storage: influxdb

metrics_preset:
  name: remotedba
  description: Metrics used for monitoring of Remote-DBA Databases
  metrics: '{"kpi": 120, "wal": 60, "locks": 60, "db_size": 300, "archiver": 60, "backends": 60, "bgwriter": 60, "cpu_load": 60, "db_stats": 60, "settings": 7200, "wal_size": 300, "locks_mode": 60, "index_stats": 900, "replication": 120, "sproc_stats": 180, "table_stats": 300, "wal_receiver": 120, "change_events": 300, "table_io_stats": 600, "sequence_health": 3600, "replication_slots": 120}' 

databases:
- host: pgwatch2-postgresql
  grafana_preset_metrics: remotedba
  port: 5432
  user: pgwatch2
  password: 'pgwatch2'
  dbs:
    - postgres
    - foo
    - bar
- host: pgwatch2-postgresql-hl
  grafana_preset_metrics: remotedba
  port: 5432
  user: pgwatch2
  password: 'pgwatch2'
  dbs:
    - postgres
    - pgwatch2

daemon:
  image:
    repository: cybertec/pgwatch2-daemon
    tag: latest
  resources: {}

bootstrap:
  image:
    repository: cybertec/pgwatch2-db-bootstrapper
    tag: latest

postgresql:
  primary:
    initdb:
      scriptsConfigMap: pgwatch2-initdb

pgadmin:
  enabled: True

influxdb:
  service:
    type: LoadBalancer

webui:
  service:
    enabled: True
    port: 80
    targetPort: 8080
    type: LoadBalancer
  image:
    repository: cybertec/pgwatch2
    tag: latest

grafana:
  enabled: True
  service:
    type: LoadBalancer
  noAnonymous: false
  user: admin
  password: pgwatch2admin # password will be auto generated if emtpy
  ldap:
    enabled: true
    config: |
      [[servers]]
      # Ldap server host (specify multiple hosts space separated)
      host = "127.0.0.1"
      # Default port is 389 or 636 if use_ssl = true
      port = 389
      # Set to true if LDAP server should use an encrypted TLS connection (either with STARTTLS or LDAPS)
      use_ssl = false
      # If set to true, use LDAP with STARTTLS instead of LDAPS
      start_tls = false
      # set to true if you want to skip SSL cert validation
      ssl_skip_verify = false
      # set to the path to your root CA certificate or leave unset to use system defaults
      # root_ca_cert = "/path/to/certificate.crt"
      # Authentication against LDAP servers requiring client certificates
      # client_cert = "/path/to/client.crt"
      # client_key = "/path/to/client.key"

      # Search user bind dn
      bind_dn = "cn=admin,dc=grafana,dc=org"
      # Search user bind password
      # If the password contains # or ; you have to wrap it with triple quotes. Ex """#password;"""
      bind_password = "grafana"

      # User search filter, for example "(cn=%s)" or "(sAMAccountName=%s)" or "(uid=%s)"
      # Allow login from email or username, example "(|(sAMAccountName=%s)(userPrincipalName=%s))"
      search_filter = "(cn=%s)"

      # An array of base dns to search through
      search_base_dns = ["dc=grafana,dc=org"]

      # group_search_filter = "(&(objectClass=posixGroup)(memberUid=%s))"
      # group_search_filter_user_attribute = "distinguishedName"
      # group_search_base_dns = ["ou=groups,dc=grafana,dc=org"]

      # Specify names of the LDAP attributes your LDAP uses
      [servers.attributes]
      member_of = "memberOf"
      email =  "email"
  grafana.ini:
    dashboards:
      default_home_dashboard_path: "/var/lib/grafana/dashboards/default/health-check.json"
    auth.ldap:
      enabled: true
      config_file: /etc/grafana/ldap.toml
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: InfluxDB_v1
        type: influxdb
        access: proxy
        url: http://pgwatch2-influxdb:8086
        isDefault: true
        database: pgwatch2
        user: pgwatch2
        jsonData:
          httpMode: GET
        secureJsonData:
          password: pgwatch2
  dashboardProviders:
   dashboardproviders.yaml:
     apiVersion: 1
     providers:
     - name: 'default'
       orgId: 1
       folder: ''
       type: file
       disableDeletion: false
       editable: true
       options:
         path: /var/lib/grafana/dashboards/default

  dashboardsConfigMaps:
    default: "grafana-dashboards"
  image:
    repository: grafana/grafana
    tag: latest

metallb:
  enabled: true
  configInline:
    address-pools:
     - name: default
       protocol: layer2
       addresses:
       - 192.168.49.10-192.168.49.250
