{
 "title": "eXperDB Global Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 26, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "with recursive recur_data(ms_hostname, ms_id, ms_hagroup_id, ms_upstream_hostname, level, path, cycle) as\r\n(\r\n\tselect \r\n\t\tmsvr.ms_hostname\r\n\t  , msvr.ms_id \r\n\t  , msvr.ms_hagroup_id \r\n\t  , msvr.ms_upstream_hostname \r\n\t  , 0\r\n\t  , array[msvr.ms_id]\r\n\t  , false \r\n\tfrom pgwatch2.monitored_server msvr\r\n\twhere msvr.ms_upstream_hostname is null \r\n\tunion all \r\n\tselect \r\n\t\tmsvr.ms_hostname \r\n\t  , msvr.ms_id \r\n\t  , msvr.ms_hagroup_id \r\n\t  , msvr.ms_upstream_hostname \r\n\t  , level + 1\r\n\t  , path || msvr.ms_id\r\n\t  , msvr.ms_id = any(path)\r\n\tfrom pgwatch2.monitored_server msvr, recur_data rd\r\n\twhere msvr.ms_upstream_hostname = rd.ms_hostname\r\n\tand not cycle \r\n)\r\nselect level, ms_hostname as ip, path as p, ms_hagroup_id as hagroup, case when level > 0 then 1\r\n      else 0\r\n    end as replicate_check from recur_data order by hagroup, path"
    },
    {
     "query": "select last(\"in_recovery_int\") FROM \"wal\" where $timeFilter group by \"ip\" "
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu_load",
     "query": "SELECT mean(\"load_5min\") FROM \"cpu_load\" WHERE $timeFilter GROUP BY ip, time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "load_5min" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "$tag_ip",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "query": "SELECT last(\"percent\") FROM \"psutil_mem\" WHERE  $timeFilter GROUP BY ip, time($__interval) fill(none)",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Session Connection",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_ip ",
     "query": " select last(\"idle\")/max_connections * 100 from \"backends\" WHERE  $timeFilter GROUP BY   ip  fill(none)"
    }
   ]
  },
  {
   "title": "Session Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_ip",
     "query": "SELECT mean(\"idle\") FROM backends where $timeFilter GROUP BY  ip, time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_ip",
     "query": "SELECT mean(\"percent\") FROM \"psutil_disk\" WHERE $timeFilter GROUP BY time($__interval), ip, \"path\" fill(none)"
    }
   ]
  },
  {
   "title": "Logical I/O Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "$tag_ip",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "query": "select \n  max(tup_deleted) - min(tup_deleted) \n  + max(tup_inserted) - min(tup_inserted)\n  + max(tup_updated) - min(tup_updated)\nfrom db_stats \nWHERE  $timeFilter \nGROUP BY dbname, ip fill(0)\n",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Logical Insert",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_ip - $tag_dbname",
     "displayType": "Regular",
     "query": "select \n  max(tup_inserted) - min(tup_inserted)\nfrom db_stats \nWHERE  $timeFilter \nGROUP BY dbname, ip fill(0)\n",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Logical Update",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_ip - $tag_dbname",
     "displayType": "Regular",
     "query": "select \n  max(tup_updated) - min(tup_updated)\nfrom db_stats \nWHERE  $timeFilter \nGROUP BY dbname, ip fill(0)\n",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Logical Delete",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_dbname",
     "displayType": "Regular",
     "query": "select \n  max(tup_deleted) - min(tup_deleted) \nfrom db_stats \nWHERE  $timeFilter \nGROUP BY dbname fill(0)\n",
     "valueHandler": "Number Threshold"
    }
   ]
  }
 ]
}