{
 "title": "eXperDB Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": "SHOW TAG VALUES WITH KEY = \"ip\" "
   },
   {
    "name": "dbname",
    "query": "select md_unique_name from monitored_db where md_hostname like '$hostname'"
   },
   {
    "name": "agg_interval",
    "query": "1s,1m,5m,10m,15m,30m,1h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  { "title": "$dbname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "dbname" },
  { "title": "Key Performance Index", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_dbname",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select last(\"in_recovery_int\") FROM \"wal\" WHERE \"dbname\" =~ /^$dbname$/ AND $timeFilter GROUP BY time(365d), dbname fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Act Slot",
     "query": "select count(\"active\") from (select last(\"active\") as \"active\" FROM \"replication_slots\" WHERE \"dbname\" =~ /^$dbname$/ AND $timeFilter group by \"dbname\", \"slot_name\") WHERE \"active\" =  true"
    },
    {
     "alias": "InAct Slot",
     "query": "select sum(last) from (select last(\"non_active_int\") FROM \"replication_slots\" WHERE \"dbname\" =~ /^$dbname$/  AND $timeFilter  group by \"slot_name\")"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 5, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Replication Delay",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "query": "SELECT mean(\"replay_lag_b\") FROM \"replication\" WHERE (\"dbname\" =~ /^$dbname$/) AND $timeFilter GROUP BY time($__interval), \"dbname\", \"client_info\", \"application_name\" fill(none)",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"cpu_utilization\") FROM \"psutil_cpu\" WHERE (\"dbname\" =~ /^$dbname$/) AND \"ip\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"used\") FROM \"psutil_mem\" WHERE (\"dbname\" =~ /^$dbname$/) AND \"ip\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 1, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"percent\") FROM \"psutil_disk\" WHERE (\"dbname\" =~ /^$dbname$/) AND \"ip\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($__interval), \"dir_or_tablespace\", \"path\" fill(none)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Write",
     "query": "SELECT non_negative_derivative(max(\"write_bytes\"), 1s) FROM \"psutil_disk_io_total\" WHERE (\"dbname\" =~ /^$dbname$/) AND \"ip\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "Read",
     "query": "SELECT non_negative_derivative(max(\"read_bytes\"), 1s) FROM \"psutil_disk_io_total\" WHERE (\"dbname\" =~ /^$dbname$/) AND \"ip\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "avg_query_runtime_per_db",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(q) from (SELECT non_negative_derivative(mean(\"total_time\")) / non_negative_derivative(mean(\"calls\")) as q FROM \"stat_statements\" WHERE \"dbname\" =~ /^$dbname$/ AND \"ip\" =~ /^$hostname$/ AND \"query\" !~ /(?i)::int8[\\s+]as[\\s]+epoch_ns/ AND $timeFilter GROUP BY queryid, time($__interval) fill(none)) group by time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Bloat size",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "table_bloat_approx_summary",
     "query": "SELECT mean(\"approx_table_bloat_b\" ) FROM \"table_bloat_approx_summary_sql\" WHERE (\"dbname\" =~/^$dbname$/) AND $timeFilter GROUP BY time(1h) fill(none)",
     "select": [
      [
       { "params": [ "approx_free_space_b" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "FROZENMAXAGE",
     "query": "SELECT max(\"tx_freeze_age\") FROM \"table_stats\" WHERE (\"dbname\" =~ /^$dbname$/) AND $timeFilter fill(none)\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select last(\"in_recovery_int\") FROM wal where ip = '$hostname' group by ip"
    },
    {
     "rawSql": "with recursive recur_data(ms_hostname, ms_id, ms_upstream_hostname, level, path, cycle) as\r\n(\r\n\tselect \r\n\t\tmsvr.ms_hostname\r\n\t  , msvr.ms_id \r\n\t  , msvr.ms_upstream_hostname \r\n\t  , 0\r\n\t  , array[msvr.ms_id]\r\n\t  , false \r\n\tfrom pgwatch2.monitored_server msvr\r\n\twhere msvr.ms_upstream_hostname is null \r\n\tunion all \r\n\tselect \r\n\t\tmsvr.ms_hostname \r\n\t  , msvr.ms_id \r\n\t  , msvr.ms_upstream_hostname \r\n\t  , level + 1\r\n\t  , path || msvr.ms_id\r\n\t  , msvr.ms_id = any(path)\r\n\tfrom pgwatch2.monitored_server msvr, recur_data rd\r\n\twhere msvr.ms_upstream_hostname = rd.ms_hostname\r\n\tand not cycle \r\n)\r\nselect level, ms_hostname as ip, path as p, case when level > 0 then 1\r\n      else 0\r\n    end as replicate_check from recur_data order by path"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"numbackends\") FROM \"db_stats\" WHERE (\"dbname\" =~ /^$dbname$/) AND $timeFilter GROUP BY time(1d) fill(none)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "swap_used",
     "query": "SELECT mean(\"swap_used\") FROM \"psutil_mem\" WHERE (\"dbname\" =~ /^$dbname$/) AND \"ip\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "TPS",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(last(\"xact_commit\"), 1s) + non_negative_derivative(last(\"xact_rollback\"), 1s) FROM \"db_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND  $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "QPS",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(last(\"calls\"), 1s) FROM \"stat_statements_calls\" WHERE $timeFilter AND \"dbname\" =~ /^$dbname$/ GROUP BY time(10m) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Longest Query",
     "query": "SELECT last(\"longest_query_seconds\") FROM \"backends\" WHERE (\"dbname\" =~ /^$dbname$/) AND $timeFilter GROUP BY time(1d) fill(none)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "query": "SELECT  non_negative_derivative(mean(\"tup_fetched\")) / non_negative_derivative(mean(\"tup_returned\")) * 100 FROM \"db_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND  $timeFilter GROUP BY time($agg_interval) fill(none)",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT ( non_negative_derivative(mean(\"blks_hit\")) / (non_negative_derivative(mean(\"blks_hit\")) + non_negative_derivative(mean(\"blks_read\")))) * 100 FROM \"db_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND \"ip\" =~ /^$hostname$/ AND  $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "db_stats",
     "query": "SELECT \"postmaster_uptime_s\" FROM \"db_stats\" WHERE (\"dbname\" =~ /^$dbname$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "postmaster_uptime_s" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Read",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select  last(\"server_version\") as server_version FROM \"settings\" WHERE \"dbname\" =~ /^$dbname$/ AND  time > now() - 6h GROUP BY dbname fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "db_size_change_last_hour",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"size_b\")  - first(\"size_b\") FROM \"db_size\" WHERE \"dbname\" =~ /^$dbname$/ AND $timeFilter GROUP BY time(1h) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Charts", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU load  And Query Runtime",
   "type": "graph",
   "description": "$agg_interval Average",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "CPU Load",
     "query": "SELECT mean(\"load_5min\") FROM \"cpu_load\" WHERE  \"ip\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($agg_interval), ip fill(none)"
    },
    {
     "alias": "Query Runtime",
     "query": "select mean(runtime) from (SELECT non_negative_derivative(last(\"total_time\"), 1h) / non_negative_derivative(last(\"calls\"), 1h) as runtime FROM \"stat_statements\" WHERE  \"ip\" =~ /^$hostname$/ AND \"query\" !~ /(?i)::int8[\\s]+as[\\s]+epoch_ns/ AND $timeFilter GROUP BY queryid, time($agg_interval) fill(none)) group by time($agg_interval), ip fill(none)"
    }
   ]
  },
  {
   "title": "Sessions by state ",
   "type": "graph",
   "description": "$agg_interval avg",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "idle",
     "groupBy": [
      { "params": [ "$agg_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "backends",
     "query": "SELECT mean(\"idle\") FROM \"backends\" WHERE (\"dbname\" =~ /^$dbname$/) AND \"ip\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($agg_interval) fill(none)",
     "select": [
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    },
    {
     "alias": "idle in transaction",
     "groupBy": [
      { "params": [ "$agg_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "backends",
     "query": "SELECT mean(\"idleintransaction\") FROM \"backends\" WHERE (\"dbname\" =~ /^$dbname$/) AND \"ip\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($agg_interval) fill(none)",
     "select": [
      [
       { "params": [ "idleintransaction" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    },
    {
     "alias": "waiting",
     "groupBy": [
      { "params": [ "$agg_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "backends",
     "query": "SELECT mean(\"waiting\") FROM \"backends\" WHERE (\"dbname\" =~ /^$dbname$/) AND \"ip\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($agg_interval) fill(none)",
     "select": [
      [
       { "params": [ "waiting" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    },
    {
     "alias": "active",
     "groupBy": [
      { "params": [ "$agg_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "backends",
     "query": "SELECT mean(\"active\") FROM \"backends\" WHERE (\"dbname\" =~ /^$dbname$/) AND \"ip\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($agg_interval) fill(none)",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    },
    {
     "alias": "av_workers",
     "groupBy": [
      { "params": [ "$agg_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "backends",
     "query": "SELECT mean(\"av_workers\") FROM \"backends\" WHERE (\"dbname\" =~ /^$dbname$/) AND \"ip\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($agg_interval) fill(none)",
     "select": [
      [
       { "params": [ "av_workers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "TPS / QPS",
   "type": "graph",
   "description": "Transactions per Second / Queries per Second",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "TPS",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "query": "SELECT non_negative_derivative(last(\"xact_commit\"), 1s) + non_negative_derivative(last(\"xact_rollback\"), 1s) FROM \"db_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND \"ip\" =~ /^$hostname$/ AND  $timeFilter GROUP BY time($agg_interval), ip fill(none)",
     "select": [
      [
       { "params": [ "numbackends" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "QPS",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "query": "SELECT non_negative_derivative(last(\"calls\"), 1s) FROM \"stat_statements_calls\" WHERE $timeFilter AND \"dbname\" =~ /^$dbname$/ AND \"ip\" =~ /^$hostname$/ GROUP BY time($agg_interval), ip fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Locks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_lockmode",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"count\") FROM \"locks_mode\" WHERE (\"dbname\" =~ /^$dbname$/) AND \"ip\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($__interval), \"lockmode\", ip fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Swap Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "swap_used",
     "query": "SELECT mean(\"swap_used\") FROM \"psutil_mem\" WHERE \"dbname\" =~ /^$dbname$/ AND \"ip\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($__interval), ip fill(none)"
    }
   ]
  },
  {
   "title": "Shared Buffers hit ratio + Rollback ratio",
   "type": "graph",
   "description": "$agg_interval avg",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Shared buffers hit ratio",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "query": "SELECT ( non_negative_derivative(mean(\"blks_hit\")) / (non_negative_derivative(mean(\"blks_hit\")) + non_negative_derivative(mean(\"blks_read\")))) * 100 FROM \"db_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND \"ip\" =~ /^$hostname$/ AND  $timeFilter GROUP BY time($agg_interval), ip fill(none)",
     "select": [
      [
       { "params": [ "blks_hit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "TX rollback ratio",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (non_negative_derivative(mean(\"xact_rollback\")) / (non_negative_derivative(mean(\"xact_commit\")) + non_negative_derivative(mean(\"xact_rollback\"))) * 100) FROM \"db_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND \"ip\" =~ /^$hostname$/ AND  $timeFilter GROUP BY time($agg_interval), ip fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "description": "Transactions per Second / Queries per Second",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "RollBack",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "query": "SELECT  non_negative_derivative(last(\"xact_rollback\"), 1s) FROM \"db_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND \"ip\" =~ /^$hostname$/ AND  $timeFilter GROUP BY time($agg_interval) fill(none)",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Commit",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "query": "SELECT non_negative_derivative(last(\"xact_commit\"), 1s) FROM \"db_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND \"ip\" =~ /^$hostname$/ AND  $timeFilter GROUP BY time($agg_interval), ip fill(none)",
     "select": [
      [
       { "params": [ "numbackends" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Query Run time",
   "type": "graph",
   "description": "Transactions per Second / Queries per Second",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Query Run Time",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "query": "SELECT non_negative_derivative(last(\"total_time\"), 1h) / non_negative_derivative(last(\"calls\"), 1h) FROM \"stat_statements_calls\" WHERE \"dbname\" =~ /^$dbname$/ AND \"ip\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($__interval), ip fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tuple  ins. / upd. / del. statistics",
   "type": "graph",
   "description": "$agg_interval avg. rate., log. scale",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "DELETE",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "query": "SELECT non_negative_derivative(mean(\"tup_deleted\"), $agg_interval) FROM \"db_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND \"ip\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($agg_interval), ip fill(none)",
     "select": [
      [
       { "params": [ "tup_deleted" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    },
    {
     "alias": "UPDATE",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"tup_updated\"), $agg_interval) FROM \"db_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND \"ip\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($agg_interval), ip fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "INSERT",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"tup_inserted\"), $agg_interval) FROM \"db_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND \"ip\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($agg_interval), ip fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "WAL rate + DB size",
   "type": "graph",
   "description": "$agg_interval avg",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "WAL rate",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wal",
     "query": "SELECT derivative(mean(\"xlog_location_b\"), 1s) FROM \"wal\" WHERE \"dbname\" =~ /^$dbname$/ AND \"ip\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($agg_interval), ip fill(none)",
     "select": [
      [
       { "params": [ "xlog_location_b" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    },
    {
     "alias": "DB Size",
     "groupBy": [
      { "params": [ "$agg_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "db_size",
     "query": "SELECT mean(\"size_b\") FROM \"db_size\" WHERE \"dbname\" =~ /^$dbname$/ AND \"ip\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($agg_interval), ip fill(none)",
     "select": [
      [
       { "params": [ "size_b" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "description": "Transactions per Second / Queries per Second",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "QPS",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "query": "SELECT non_negative_derivative(last(\"calls\"), 1s) FROM \"stat_statements_calls\" WHERE $timeFilter AND \"dbname\" =~ /^$dbname$/ AND \"ip\" =~ /^$hostname$/ GROUP BY time($agg_interval), ip fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Seq. / Idx. scans",
   "type": "graph",
   "description": "$agg_interval avg., >10MB tables, log. scale",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu_load",
     "query": "select sum(seq_scan) as seq_scan,  sum(idx_scan) as idx_scan from (SELECT non_negative_derivative(mean(\"seq_scan\"), $agg_interval) as seq_scan, non_negative_derivative(mean(\"idx_scan\"), $agg_interval) as idx_scan FROM \"table_stats\" WHERE (\"dbname\" =~ /^$dbname$/) AND \"ip\" =~ /^$hostname$/ AND $timeFilter AND table_size_b > 10000000 GROUP BY time($agg_interval), table_full_name fill(none)) GROUP BY time($agg_interval) fill(none)",
     "select": [
      [
       { "params": [ "load_5min" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temp bytes",
   "type": "graph",
   "description": "$agg_interval avg",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu_load",
     "query": "SELECT mean(temp_bytes) as temp_bytes FROM (SELECT non_negative_derivative(\"temp_bytes\", $agg_interval) as temp_bytes FROM \"db_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND \"ip\" =~ /^$hostname$/ AND  $timeFilter) GROUP BY time($agg_interval) fill(none)",
     "select": [
      [
       { "params": [ "load_5min" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}