apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgwatch2.fullname" . }}-initdb
data:
  initdb.sql: |
    CREATE USER {{ .Values.postgresql.user | default "pgwatch2" }} WITH PASSWORD '{{ .Values.postgresql.password | default "pgwatch2" }}';
    CREATE DATABASE {{ .Values.postgresql.database | default "pgwatch2" }};
    GRANT ALL PRIVILEGES ON DATABASE {{ .Values.postgresql.database | default "pgwatch2" }} TO {{ .Values.postgresql.user | default "pgwatch2" }};
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgwatch2.fullname" . }}-influxdb-init
data:
  influxdb-init.iql: |
    CREATE DATABASE {{ .Values.influxdb.database | default "pgwatch2" }};
    CREATE RETENTION POLICY pgwatch_def_ret ON {{ .Values.influxdb.database | default "pgwatch2" }} DURATION 30d REPLICATION 1 DEFAULT;
