{{ if .Values.webui.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "pgwatch2.fullname" . }}-webui
  labels:
    {{- include "pgwatch2.labels" . | nindent 4 }}
{{- if .Values.webui.service.labels }}
{{ toYaml .Values.webui.service.labels | indent 4 }}
{{- end }}
{{- with .Values.webui.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if (or (eq .Values.webui.service.type "ClusterIP") (empty .Values.webui.service.type)) }}
  type: ClusterIP
  {{- if .Values.webui.service.clusterIP }}
  clusterIP: {{ .Values.webui.service.clusterIP }}
  {{end}}
{{- else if eq .Values.webui.service.type "LoadBalancer" }}
  type: {{ .Values.webui.service.type }}
  {{- if .Values.webui.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.webui.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.webui.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.webui.service.loadBalancerSourceRanges | indent 4 }}
  {{- end -}}
{{- else }}
  type: {{ .Values.webui.service.type }}
{{- end }}
{{- if .Values.webui.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.webui.service.externalIPs | indent 4 }}
{{- end }}
  ports:
    - name: {{ .Values.webui.service.portName }}
      port: {{ .Values.webui.service.port }}
      protocol: TCP
      targetPort: {{ .Values.webui.service.targetPort }}
{{ if (and (eq .Values.webui.service.type "NodePort") (not (empty .Values.webui.service.nodePort))) }}
      nodePort: {{.Values.webui.service.nodePort}}
{{ end }}
  {{- if .Values.webui.extraExposePorts }}
  {{- tpl (toYaml .Values.webui.extraExposePorts) . | indent 4 }}
  {{- end }}
  selector:
    {{- include "webui.selectorLabels" . | nindent 4 }}
{{ end }}
