{
 "title": "Global eXperDB Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 26, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "with recursive recur_data(md_hostname, md_unique_name, md_id, md_upid, md_hagroup, level, path, cycle) as\r\n(\r\n\tselect \r\n\t\tmdb.md_hostname \r\n\t  , mdb.md_unique_name \r\n\t  , mdb.md_id \r\n\t  , mdb.md_upid \r\n\t  , mdb.md_hagroup \r\n\t  , 0\r\n\t  , array[mdb.md_id]\r\n\t  , false \r\n\tfrom pgwatch2.monitored_db mdb\r\n\twhere mdb.md_upid is null \r\n\tunion all \r\n\tselect \r\n\t\tmdb.md_hostname \r\n\t  , mdb.md_unique_name \r\n\t  , mdb.md_id \r\n\t  , mdb.md_upid \r\n\t  , mdb.md_hagroup \r\n\t  , level + 1\r\n\t  , path || rd.md_id\r\n\t  , mdb.md_id = any(path)\r\n\tfrom pgwatch2.monitored_db mdb, recur_data rd\r\n\twhere mdb.md_upid = rd.md_id \r\n)\r\nselect level, md_unique_name, md_hostname from recur_data order by path"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "timeseries",
   "description": "Requires according \"metric fetching helpers\" on the monitored server",
   "gridPos": { "h": 9, "w": 11, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_dbname",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu_load",
     "query": "SELECT mean(\"load_5min\") FROM \"cpu_load\" WHERE $timeFilter GROUP BY dbname, time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "load_5min" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "$tag_dbname",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "query": "SELECT mean(\"percent\") FROM \"psutil_mem\" WHERE  $timeFilter GROUP BY dbname, time($__interval) fill(none)",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Session Connection",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_dbname",
     "query": " select last(\"idle\")/max_connections * 100 from \"backends\" WHERE  $timeFilter GROUP BY dbname, time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "Session Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_dbname",
     "query": "SELECT mean(\"idle\") FROM backends where $timeFilter GROUP BY  dbname, time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_dbname",
     "query": "SELECT mean(\"percent\") FROM \"psutil_disk\" WHERE $timeFilter GROUP BY time($__interval), dbname, \"path\" fill(none)"
    }
   ]
  },
  {
   "title": "Disk I/O Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "$tag_dbname",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "query": "select \n  max(tup_deleted) - min(tup_deleted) \n  + max(tup_inserted) - min(tup_inserted)\n  + max(tup_updated) - min(tup_updated)\nfrom db_stats \nWHERE  $timeFilter \nGROUP BY dbname fill(0)\n",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Disk Insert",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_dbname",
     "displayType": "Regular",
     "query": "select \n  max(tup_inserted) - min(tup_inserted)\nfrom db_stats \nWHERE  $timeFilter \nGROUP BY dbname fill(0)\n",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Disk Update",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_dbname",
     "displayType": "Regular",
     "query": "select \n  max(tup_updated) - min(tup_updated)\nfrom db_stats \nWHERE  $timeFilter \nGROUP BY dbname fill(0)\n",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Disk Delete",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_dbname",
     "displayType": "Regular",
     "query": "select \n  max(tup_deleted) - min(tup_deleted) \nfrom db_stats \nWHERE  $timeFilter \nGROUP BY dbname fill(0)\n",
     "valueHandler": "Number Threshold"
    }
   ]
  }
 ]
}