{
 "title": "eXperDB Overview",
 "description": "Current and avg. KPI-s. Expects 'get_load_average' and 'backends'  helpers to be installed on the monitored DB.",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dbname",
    "query": "SHOW TAG VALUES FROM \"wal\", \"db_stats\" WITH KEY = \"dbname\" WHERE time > now() - 1h"
   },
   { "name": "online_interval", "label": "Max. age for 'online' metrics", "query": "1m,3m,5m,10m,15m" },
   {
    "name": "md_group",
    "query": "select md_group from monitored_db group by md_group order by md_group;"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "crit": 1000000,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "measurement": "backends",
     "query": "select numbackends  from kpi limit 1",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       { "params": [ "Fine" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ],
     "units": "none",
     "valueHandler": "Text Only",
     "warn": 1000000
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "crit": 1000000,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "measurement": "backends",
     "query": "select numbackends - 1 from kpi limit 1",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       { "params": [ "Fine" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ],
     "units": "none",
     "valueHandler": "Text Only",
     "warn": 1000000
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "crit": 1000000,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "measurement": "backends",
     "query": "select numbackends - 9 from kpi limit 1",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       { "params": [ "Fine" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ],
     "units": "none",
     "valueHandler": "Text Only",
     "warn": 1000000
    }
   ]
  },
  {
   "title": "CPU load(Top 5)",
   "type": "table",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "dbname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_load",
     "query": "SELECT max(\"load_5min\") FROM \"cpu_load\" WHERE $timeFilter GROUP BY \"dbname\" fill(null) slimit 5",
     "select": [
      [
       { "params": [ "/^$dbname$/" ], "type": "field" }
      ],
      [
       { "params": [ "load_5min" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory used(Top 5)",
   "type": "table",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "dbname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_load",
     "query": "SELECT max(\"load_5min\") FROM \"cpu_load\" WHERE $timeFilter GROUP BY \"dbname\" fill(null) slimit 5",
     "select": [
      [
       { "params": [ "/^$dbname$/" ], "type": "field" }
      ],
      [
       { "params": [ "load_5min" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "IO Wait (Top 5)",
   "type": "table",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "dbname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_load",
     "query": "SELECT dbname, max(\"load_5min\") FROM \"cpu_load\" WHERE $timeFilter GROUP BY time($__interval)  fill(none) limit 5",
     "select": [
      [
       { "params": [ "/^$dbname$/" ], "type": "field" }
      ],
      [
       { "params": [ "load_5min" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Sessions(Top 5)",
   "type": "table",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "dbname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_load",
     "query": "SELECT max(\"load_5min\") FROM \"cpu_load\" WHERE $timeFilter GROUP BY \"dbname\" fill(null) slimit 5",
     "select": [
      [
       { "params": [ "/^$dbname$/" ], "type": "field" }
      ],
      [
       { "params": [ "load_5min" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alert event history",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "SELECT max(\"cpu_utilization\") as \"Alert Count\" FROM \"psutil_cpu\" WHERE  $timeFilter   group by time(3m) fill(null)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "crit": 1000000,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "measurement": "backends",
     "query": "select numbackends - 4 from kpi limit 1",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       { "params": [ "Fine" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ],
     "units": "none",
     "valueHandler": "Text Only",
     "warn": 1000000
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Warning",
     "crit": 1000000,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "measurement": "backends",
     "query": "select numbackends - 7 from kpi limit 1",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       { "params": [ "Fine" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ],
     "units": "none",
     "valueHandler": "Text Only",
     "warn": 1000000
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Fine",
     "crit": 1000000,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "measurement": "backends",
     "query": "select numbackends - 9 from kpi limit 1",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       { "params": [ "Fine" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ],
     "units": "none",
     "valueHandler": "Text Only",
     "warn": 1000000
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 6 },
   "repeat": "md_group",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select md_unique_name as dbname from monitored_db where  \"md_group\" = $md_group order by md_id;\n"
    },
    {
     "aggregation": "Max",
     "crit": 10,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Annotation",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "backends",
     "query": "select continuous_discovery_prefix, max(\"group\") from configured_dbs where $timeFilter AND \"group\" = '$md_group' ",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Active Sessions" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 9 },
   "repeat": "md_group",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select md_unique_name as dbname from monitored_db where  \"md_group\" = $md_group order by md_id;\n"
    },
    {
     "aggregation": "Max",
     "crit": 10,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Annotation",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "backends",
     "query": "select continuous_discovery_prefix, max(\"group\") from configured_dbs where $timeFilter AND \"group\" = '$md_group' ",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Active Sessions" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 12 },
   "repeat": "md_group",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select md_unique_name as dbname from monitored_db where  \"md_group\" = $md_group order by md_id;\n"
    },
    {
     "aggregation": "Max",
     "crit": 10,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Annotation",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "backends",
     "query": "select continuous_discovery_prefix, max(\"group\") from configured_dbs where $timeFilter AND \"group\" = '$md_group' ",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Active Sessions" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 15 },
   "repeat": "md_group",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select md_unique_name as dbname from monitored_db where  \"md_group\" = $md_group order by md_id;\n"
    },
    {
     "aggregation": "Max",
     "crit": 10,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Annotation",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "backends",
     "query": "select continuous_discovery_prefix, max(\"group\") from configured_dbs where $timeFilter AND \"group\" = '$md_group' ",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Active Sessions" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 7, "x": 1, "y": 18 },
   "options": {
    "content": " <a href=\"https://github.com/kayform\"><img src=\"https://raw.githubusercontent.com/kayform/DX-Management/master/KakaoTalk_20220509_175039729.png\" alt=\"Inzent – The PostgreSQL Database Company\"></a>\n\n"
   }
  }
 ]
}